<?php 
if( function_exists('acf_add_local_field_group') ):
	// GROUP : Custom block Related Content
    acf_add_local_field_group(array(
        'key' => 'group_5d80ab6e372f7',
        'title' => 'Custom block Related Content',
        'fields' => array(
            array(
                'key' => 'field_5d80ab6e4602c',
                'label' => 'Titre de la zone',
                'name' => 'relatedContentTitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
				'key' => 'field_5dd2cdab2dca8',
				'label' => 'Affichage',
				'name' => 'sedoo-relatedcontent-list-layout',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'list' => 'Liste',
					'grid' => 'Grille',
					'grid-noimage' => 'Grille sans image',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'list',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
            array(
                'key' => 'field_5d80ab6e46017',
                'label' => 'Type de contenu',
                'name' => 'relatedContentTypeOfContent',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'location' => 'Emplacements',
                    'event' => 'Évènements',
                    'feedzy_categories' => 'Feed Categories',
                    'sedoo-platform' => 'Plateformes',
                    'sedoo-research-team' => 'Équipes de recherche',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d80ab6e46031',
                'label' => 'Taxonomie',
                'name' => 'relatedContentTaxonomies',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'event-tags' => 'Étiquettes d’évènement',
                    'event-categories' => 'Catégories',
                    'sedoo-theme-labo' => 'Thématiques',
                    'sedoo-platform-tag' => 'Platform Tags',
                    'sedoo-research-team-tag' => 'Research Team Tags',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                    'key' => 'field_5ecd14fbefc07',
                    'label' => 'Tout afficher en une page ?',
                    'name' => 'tout_afficher_en_une_page',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),    
            array(
                'key' => 'field_5d84ab6e45462c',
                'label' => 'Limite',
                'name' => 'sedoo_related_showmlimit',
                'type' => 'range',
				'instructions' => 'Le nombre de post affichés. 0 pour tous',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5ecd14fbefc07',
                            'operator' => '!=',
                            'value' => '0',
                        ),
                    ),
                ),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5ecd150eefc08',
                'label' => 'Nombre par page ?',
                'name' => 'post_number',
                'type' => 'range',
                'instructions' => 'Set 0 for unlimited, défault 10',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5ecd14fbefc07',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '10',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d80ab6e4752c',
                'label' => 'Bouton Voir plus',
                'name' => 'sedoo_related_showmorecontent',
                'type' => 'true_false',
				'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5ecd14fbefc07',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                    ),
                ),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5d80ab6e4842c',
                'label' => 'Texte du bouton Voir plus',
                'name' => 'sedoo_related_showmorecontent_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5ecd14fbefc07',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                        array(
                            'field' => 'field_5d80ab6e4752c',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Voir plus',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d80ab6e4603c',
                'label' => 'Offset',
                'name' => 'post_offset',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/sedoo-labtools-relatedblock',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    

endif;
?>