<?php 
	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_5e68db81c2aa2',
			'title' => 'champs iframe',
			'fields' => array(
				array(
					'key' => 'field_5e68db9739c08',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e68e03cc0e3f',
					'label' => 'Requête',
					'name' => 'requete',
					'type' => 'text',
					'instructions' => 'A renseigner si vous désirez passer un élément de requête dans l\'url',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e68dbc839c09',
					'label' => 'hauteur',
					'name' => 'hauteur',
					'type' => 'number',
					'instructions' => 'En pixel',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1000,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5e68dca56a00e',
					'label' => 'Largeur',
					'name' => 'largeur',
					'type' => 'number',
					'instructions' => 'En pourcentage',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 100,
					'placeholder' => '',
					'prepend' => '',
					'append' => '%',
					'min' => 1,
					'max' => 100,
					'step' => '',
				),
				array(
					'key' => 'field_5e68e29e3d477',
					'label' => 'Attributs Supplémentaires',
					'name' => 'attributs_supplementaires',
					'type' => 'text',
					'instructions' => 'Permet d\'ajouter des attributs supplémentaires sous la forme attribut="valeur"',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f19582bd00ae',
					'label' => 'Classe du container',
					'name' => 'classe_du_container',
					'type' => 'text',
					'instructions' => 'Ajoute une classe personnalisé au container de l\'iframe',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e68e19273bb3',
					'label' => 'Scrolling',
					'name' => 'scrolling',
					'type' => 'true_false',
					'instructions' => 'Active le scroll ou non sur l\'iframe',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/sedoo-iframe',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
		));
		
		endif;
?>