<?php 
	if( function_exists('acf_add_local_field_group') ):

		acf_add_local_field_group(array(
			'key' => 'group_5e68db81c2aa2',
			'title' => 'champs iframe',
			'fields' => array(
				array(
					'key' => 'field_5e68db9739c08',
					'label' => 'URL',
					'name' => 'url',
					'type' => 'url',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e68e03cc0e3f',
					'label' => __('Request', 'sedoo-wppl-blocks'),
					'name' => 'requete',
					'type' => 'text',
					'instructions' => __('Needed to pass a custom request element in the url', 'sedoo-wppl-blocks'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e68dbc839c09',
					'label' => __('Height', 'sedoo-wppl-blocks'),
					'name' => 'hauteur',
					'type' => 'number',
					'instructions' => __('In px', 'sedoo-wppl-blocks'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1000,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5e68dca56a00e',
					'label' => __('Width', 'sedoo-wppl-blocks'),
					'name' => 'largeur',
					'type' => 'number',
					'instructions' => __('In %', 'sedoo-wppl-blocks'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 100,
					'placeholder' => '',
					'prepend' => '',
					'append' => '%',
					'min' => 1,
					'max' => 100,
					'step' => '',
				),
				array(
					'key' => 'field_5e68e29e3d477',
					'label' => __('Add custom attributes', 'sedoo-wppl-blocks'),
					'name' => 'attributs_supplementaires',
					'type' => 'text',
					'instructions' => __('Add custom attributes on the iframe with this format : key="value', 'sedoo-wppl-blocks'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f19582bd00ae',
					'label' => __('Container class', 'sedoo-wppl-blocks'),
					'name' => 'classe_du_container',
					'type' => 'text',
					'instructions' => __('Add a custom class on the iframe container', 'sedoo-wppl-blocks'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5e68e19273bb3',
					'label' => 'Scrolling',
					'name' => 'scrolling',
					'type' => 'true_false',
					'instructions' => __('Activate or not the scroll on the Iframe', 'sedoo-wppl-blocks'),
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'block',
						'operator' => '==',
						'value' => 'acf/sedoo-iframe',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => true,
			'description' => '',
		));
		
		endif;
?>