<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5e6b87e3ec2fc',
        'title' => __( 'Blocks activation', 'sedoo-wppl-blocks' ),
        'fields' => array(
            array(
                'key' => 'field_5e6b87eb0bd85',
                'label' => 'Block Apirest',
                'name' => 'sedoo_activation_apirest',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate APIREST block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ), 
            array(
                'key' => 'field_5e6b87eb0bd91',
                'label' => 'Block Iframe',
                'name' => 'sedoo_activation_iframe',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate Iframe block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5g6b87ed0bd25',
                'label' => 'Block RelatedContents',
                'name' => 'sedoo_activation_relatedcontents',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate related content block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e6b8e14c425a',
                'label' => __('Block member directory', 'sedoo-wppl-blocks' ),
                'name' => 'sedoo_activation_annuaire',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate member directory block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e6b96cac2e28',
                'label' => __('Block Q&A', 'sedoo-wppl-blocks' ),
                'name' => 'sedoo_activation_faq',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate Q&A block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array( 
                'key' => 'field_5e6f560a64e4d',
                'label' => __('Block post list', 'sedoo-wppl-blocks' ),
                'name' => 'sedoo_activation_listearticle',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate post list block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e3b87eb6bd76',
                'label' => __('Block content list', 'sedoo-wppl-blocks' ),
                'name' => 'sedoo_activation_listecpt',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate content list block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e6b87eb0bd23',
                'label' => __('Block page list', 'sedoo-wppl-blocks' ),
                'name' => 'sedoo_activation_listepages',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate page list block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_5e73658813c94',
                'label' => __('Block buttons', 'sedoo-wppl-blocks' ),
                'name' => 'sedoo_activation_boutons',
                'type' => 'true_false',
                'instructions' => __( 'Activate or deactivate buttons block', 'sedoo-wppl-blocks' ),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-activation-des-blocks',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;
?>