<?php 
if( function_exists('acf_add_local_field_group') ):
	acf_add_local_field_group(array(
		'key' => 'group_5dd2c81d8ff6f',
		'title' => 'Block : Post list with layout',
		'fields' => array(
			array(
				'key' => 'field_5dd2c8332dce6',
				'label' => __('Title', 'sedoo-wppl-blocks'),
				'name' => 'sedoo-block-post-list-title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fdb36641a72e',
				'label' => __('Filter type', 'sedoo-wppl-blocks'),
				'name' => 'type_de_filtre',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'category' => 'Catégories',
					'cestag' => 'CES Tags (only for Theia website)',
					'post_tag' => 'Tags',
				),
				'default_value' => array(
					0 => 'category: Catégories',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5dd2cab92dce7',
				'label' => 'Categories',
				'name' => 'sedoo-block-post-list-categories',
				'type' => 'taxonomy',
				'instructions' =>  __('No filter if empty field', 'sedoo-wppl-blocks'),
				'required' => 0,'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fdb36641a72e',
							'operator' => '==',
							'value' => 'category',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'category',
				'field_type' => 'radio',
				'allow_null' => 1,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5dh4cab21dce7',
				'label' => 'Tags',
				'name' => 'sedoo-block-post-list-tags',
				'type' => 'taxonomy',
				'instructions' =>  __('No filter if empty field', 'sedoo-wppl-blocks'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fdb36641a72e',
							'operator' => '==',
							'value' => 'cestag',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'cestag',
				'field_type' => 'radio',
				'allow_null' => 1,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array(
				'key' => 'field_4dh4cab51dce9',
				'label' => 'Tags',
				'name' => 'sedoo-block-post-list-posttags',
				'type' => 'taxonomy',
				'instructions' => __('No filter if empty field', 'sedoo-wppl-blocks'),
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fdb36641a72e',
							'operator' => '==',
							'value' => 'post_tag',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'post_tag',
				'field_type' => 'radio',
				'allow_null' => 1,
				'add_term' => 0,
				'save_terms' => 0,
				'load_terms' => 0,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array(
				'key' => 'field_5dd2cdab2dce8',
				'label' =>  __('Layout', 'sedoo-wppl-blocks'),
				'name' => 'sedoo-block-post-list-layout',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'list' => __('List', 'sedoo-wppl-blocks'),
					'grid' => __('Grid', 'sedoo-wppl-blocks'),
					'grid-noimage' => __('Grid no image', 'sedoo-wppl-blocks'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'list',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5dd2ce1a2dce9',
				'label' => __('Limit', 'sedoo-wppl-blocks'),
				'name' => 'sedoo-block-post-list-limit',
				'type' => 'number',
				'instructions' => __('Default 6 items, max allowed 18 items', 'sedoo-wppl-blocks'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 6,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '18',
				'step' => '',
			),
			array(
				'key' => 'field_5dd2ce5e2dcea',
				'label' => 'Offset',
				'name' => 'sedoo-block-post-list-offset',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 9,
				'step' => '',
			),
			array(
				'key' => 'field_5dd6a71dc219d',
				'label' => __('Display "Show more" button ?', 'sedoo-wppl-blocks'),
				'name' => 'sedoo-block-post-list-showmore-button',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5ddfed8767c61',
				'label' => __('"Show more" button label', 'sedoo-wppl-blocks'),
				'name' => 'sedoo-block-post-list-showmore-button-label',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => __('Show more', 'sedoo-wppl-blocks'),
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dd6a71dc225d',
				'label' => __('Display categories ?', 'sedoo-wppl-blocks'),
				'name' => 'sedoo-block-post-list-showterms-button',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/postlist',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
    endif;

?>